export const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL||"";
export const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"";
export type Submission={id:string;reference_no:string;district:string;school_name:string;participant1_name:string;participant1_birth_cert:string;participant1_parent_form:string;participant1_media_form:string;participant2_name:string;participant2_birth_cert:string;participant2_parent_form:string;participant2_media_form:string;teacher_name:string;teacher_ic:string;teacher_phone:string;video_url:string;status:string;created_at:string};
export const configured=()=>Boolean(SUPABASE_URL&&SUPABASE_KEY);
const headers=(token?:string)=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${token||SUPABASE_KEY}`,"Content-Type":"application/json"});
export async function api(path:string,options:RequestInit={},token?:string){const res=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:{...headers(token),...(options.headers||{})}});if(!res.ok)throw new Error((await res.text())||"Permintaan gagal");return res.status===204?null:res.json()}
export async function upload(bucket:string,file:File,onProgress:(n:number)=>void,token?:string){const name=`${Date.now()}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;return new Promise<string>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",`${SUPABASE_URL}/storage/v1/object/${bucket}/${name}`);xhr.setRequestHeader("apikey",SUPABASE_KEY);xhr.setRequestHeader("Authorization",`Bearer ${token||SUPABASE_KEY}`);xhr.setRequestHeader("Content-Type",file.type);xhr.upload.onprogress=e=>e.lengthComputable&&onProgress(Math.round(e.loaded/e.total*100));xhr.onload=()=>xhr.status<300?resolve(`${SUPABASE_URL}/storage/v1/object/public/${bucket}/${name}`):reject(new Error(xhr.responseText||"Muat naik gagal"));xhr.onerror=()=>reject(new Error("Sambungan muat naik terputus"));xhr.send(file)})}
export async function signIn(email:string,password:string){return api("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})})}

